/*
 * Your Project API
 *
 * Your project description
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

use serde_repr::{Serialize_repr,Deserialize_repr};
/// AccelerationMethodEnum : * `1` - Wegstein * `2` - Dominant Eigenvalue * `3` - Globalbroyden
/// * `1` - Wegstein * `2` - Dominant Eigenvalue * `3` - Globalbroyden
#[repr(i64)]
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize_repr, Deserialize_repr)]
pub enum AccelerationMethodEnum {
    Variant1 = 1,
    Variant2 = 2,
    Variant3 = 3,

}

impl ToString for AccelerationMethodEnum {
    fn to_string(&self) -> String {
        match self {
            Self::Variant1 => String::from("1"),
            Self::Variant2 => String::from("2"),
            Self::Variant3 => String::from("3"),
        }
    }
}
impl Default for AccelerationMethodEnum {
    fn default() -> AccelerationMethodEnum {
        Self::Variant1
    }
}

