/*
 * Your Project API
 *
 * Your project description
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AccelerationMethodEnum : * `1` - Wegstein * `2` - Dominant Eigenvalue * `3` - Globalbroyden
/// * `1` - Wegstein * `2` - Dominant Eigenvalue * `3` - Globalbroyden
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum AccelerationMethodEnum {
    #[serde(rename = "1")]
    Variant1,
    #[serde(rename = "2")]
    Variant2,
    #[serde(rename = "3")]
    Variant3,

}

impl std::fmt::Display for AccelerationMethodEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Variant1 => write!(f, "1"),
            Self::Variant2 => write!(f, "2"),
            Self::Variant3 => write!(f, "3"),
        }
    }
}

impl Default for AccelerationMethodEnum {
    fn default() -> AccelerationMethodEnum {
        Self::Variant1
    }
}

