/*
 * Your Project API
 *
 * Your project description
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AdjustCalculationModeEnum : * `Secant` - Secant * `Brent` - Brent * `Newton` - Newton * `IPOPT` - Ipopt
/// * `Secant` - Secant * `Brent` - Brent * `Newton` - Newton * `IPOPT` - Ipopt
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum AdjustCalculationModeEnum {
    #[serde(rename = "Secant")]
    Secant,
    #[serde(rename = "Brent")]
    Brent,
    #[serde(rename = "Newton")]
    Newton,
    #[serde(rename = "IPOPT")]
    Ipopt,

}

impl std::fmt::Display for AdjustCalculationModeEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Secant => write!(f, "Secant"),
            Self::Brent => write!(f, "Brent"),
            Self::Newton => write!(f, "Newton"),
            Self::Ipopt => write!(f, "IPOPT"),
        }
    }
}

impl Default for AdjustCalculationModeEnum {
    fn default() -> AdjustCalculationModeEnum {
        Self::Secant
    }
}

