/*
 * Your Project API
 *
 * Your project description
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CompressorCalculationModeEnum : * `OutletPressure` - Outletpressure * `Delta_P` - Delta P * `EnergyStream` - Energystream * `PowerRequired` - Powerrequired * `Head` - Head * `Curves` - Curves
/// * `OutletPressure` - Outletpressure * `Delta_P` - Delta P * `EnergyStream` - Energystream * `PowerRequired` - Powerrequired * `Head` - Head * `Curves` - Curves
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum CompressorCalculationModeEnum {
    #[serde(rename = "OutletPressure")]
    OutletPressure,
    #[serde(rename = "Delta_P")]
    DeltaP,
    #[serde(rename = "EnergyStream")]
    EnergyStream,
    #[serde(rename = "PowerRequired")]
    PowerRequired,
    #[serde(rename = "Head")]
    Head,
    #[serde(rename = "Curves")]
    Curves,

}

impl std::fmt::Display for CompressorCalculationModeEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::OutletPressure => write!(f, "OutletPressure"),
            Self::DeltaP => write!(f, "Delta_P"),
            Self::EnergyStream => write!(f, "EnergyStream"),
            Self::PowerRequired => write!(f, "PowerRequired"),
            Self::Head => write!(f, "Head"),
            Self::Curves => write!(f, "Curves"),
        }
    }
}

impl Default for CompressorCalculationModeEnum {
    fn default() -> CompressorCalculationModeEnum {
        Self::OutletPressure
    }
}

