/*
 * Your Project API
 *
 * Your project description
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

use serde_repr::{Serialize_repr,Deserialize_repr};
/// ConTypeEnum : * `3` - Conin * `1` - Conout * `0` - Conen * `2` - Consp
/// * `3` - Conin * `1` - Conout * `0` - Conen * `2` - Consp
#[repr(i64)]
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize_repr, Deserialize_repr)]
pub enum ConTypeEnum {
    Variant3 = 3,
    Variant1 = 1,
    Variant0 = 0,
    Variant2 = 2,

}

impl ToString for ConTypeEnum {
    fn to_string(&self) -> String {
        match self {
            Self::Variant3 => String::from("3"),
            Self::Variant1 => String::from("1"),
            Self::Variant0 => String::from("0"),
            Self::Variant2 => String::from("2"),
        }
    }
}
impl Default for ConTypeEnum {
    fn default() -> ConTypeEnum {
        Self::Variant3
    }
}

