/*
 * Your Project API
 *
 * Your project description
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConnectNewMaterialStream {
    #[serde(rename = "unitOp")]
    pub unit_op: Box<models::DjangoObject>,
    #[serde(rename = "portIndex")]
    pub port_index: i32,
}

impl ConnectNewMaterialStream {
    pub fn new(unit_op: models::DjangoObject, port_index: i32) -> ConnectNewMaterialStream {
        ConnectNewMaterialStream {
            unit_op: Box::new(unit_op),
            port_index,
        }
    }
}

