/*
 * Your Project API
 *
 * Your project description
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};


#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConnectObject {
    #[serde(rename = "unitOp")]
    pub unit_op: Box<models::DjangoObject>,
    #[serde(rename = "materialStream")]
    pub material_stream: Box<models::DjangoObject>,
    #[serde(rename = "conType")]
    pub con_type: models::ConTypeEnum,
    #[serde(rename = "portIndex", skip_serializing_if = "Option::is_none")]
    pub port_index: Option<i32>,
}

impl ConnectObject {
    pub fn new(unit_op: models::DjangoObject, material_stream: models::DjangoObject, con_type: models::ConTypeEnum) -> ConnectObject {
        ConnectObject {
            unit_op: Box::new(unit_op),
            material_stream: Box::new(material_stream),
            con_type,
            port_index: None,
        }
    }
}

