/*
 * Your Project API
 *
 * Your project description
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};


/// DefinedFlowEnum : * `Mass` - Mass * `Mole` - Mole * `Volumetric` - Volumetric
/// * `Mass` - Mass * `Mole` - Mole * `Volumetric` - Volumetric
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum DefinedFlowEnum {
    #[serde(rename = "Mass")]
    Mass,
    #[serde(rename = "Mole")]
    Mole,
    #[serde(rename = "Volumetric")]
    Volumetric,

}

impl std::fmt::Display for DefinedFlowEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Mass => write!(f, "Mass"),
            Self::Mole => write!(f, "Mole"),
            Self::Volumetric => write!(f, "Volumetric"),
        }
    }
}

impl Default for DefinedFlowEnum {
    fn default() -> DefinedFlowEnum {
        Self::Mass
    }
}

