/*
 * Your Project API
 *
 * Your project description
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};


#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DisconnectObject {
    #[serde(rename = "unitOp")]
    pub unit_op: Box<models::DjangoObject>,
    #[serde(rename = "materialStream")]
    pub material_stream: Box<models::DjangoObject>,
    #[serde(rename = "conType")]
    pub con_type: models::ConTypeEnum,
}

impl DisconnectObject {
    pub fn new(unit_op: models::DjangoObject, material_stream: models::DjangoObject, con_type: models::ConTypeEnum) -> DisconnectObject {
        DisconnectObject {
            unit_op: Box::new(unit_op),
            material_stream: Box::new(material_stream),
            con_type,
        }
    }
}

