/*
 * Your Project API
 *
 * Your project description
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DjangoObject {
    #[serde(rename = "pk")]
    pub pk: i32,
    #[serde(rename = "objectClass")]
    pub object_class: models::ObjectClassEnum,
}

impl DjangoObject {
    pub fn new(pk: i32, object_class: models::ObjectClassEnum) -> DjangoObject {
        DjangoObject {
            pk,
            object_class,
        }
    }
}

