/*
 * Your Project API
 *
 * Your project description
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DynamicsSpecEnum : * `Pressure` - Pressure * `Flow` - Flow
/// * `Pressure` - Pressure * `Flow` - Flow
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum DynamicsSpecEnum {
    #[serde(rename = "Pressure")]
    Pressure,
    #[serde(rename = "Flow")]
    Flow,

}

impl std::fmt::Display for DynamicsSpecEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Pressure => write!(f, "Pressure"),
            Self::Flow => write!(f, "Flow"),
        }
    }
}

impl Default for DynamicsSpecEnum {
    fn default() -> DynamicsSpecEnum {
        Self::Pressure
    }
}

