/*
 * Your Project API
 *
 * Your project description
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

use serde_repr::{Serialize_repr,Deserialize_repr};
/// ExchangerTypeEnum : * `0` - Doublepipe * `1` - Shelltubes E * `2` - Shelltubes F * `3` - Shelltubes G * `4` - Shelltubes H * `5` - Shelltubes J * `6` - Shelltubes K * `7` - Shelltubes X
/// * `0` - Doublepipe * `1` - Shelltubes E * `2` - Shelltubes F * `3` - Shelltubes G * `4` - Shelltubes H * `5` - Shelltubes J * `6` - Shelltubes K * `7` - Shelltubes X
#[repr(i64)]
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize_repr, Deserialize_repr)]
pub enum ExchangerTypeEnum {
    Variant0 = 0,
    Variant1 = 1,
    Variant2 = 2,
    Variant3 = 3,
    Variant4 = 4,
    Variant5 = 5,
    Variant6 = 6,
    Variant7 = 7,

}

impl ToString for ExchangerTypeEnum {
    fn to_string(&self) -> String {
        match self {
            Self::Variant0 => String::from("0"),
            Self::Variant1 => String::from("1"),
            Self::Variant2 => String::from("2"),
            Self::Variant3 => String::from("3"),
            Self::Variant4 => String::from("4"),
            Self::Variant5 => String::from("5"),
            Self::Variant6 => String::from("6"),
            Self::Variant7 => String::from("7"),
        }
    }
}
impl Default for ExchangerTypeEnum {
    fn default() -> ExchangerTypeEnum {
        Self::Variant0
    }
}

