/*
 * Your Project API
 *
 * Your project description
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FlowsheetPropertyPackage {
    #[serde(rename = "flowsheet")]
    pub flowsheet: i32,
    #[serde(rename = "property_package")]
    pub property_package: i32,
    #[serde(rename = "property_package_name")]
    pub property_package_name: String,
}

impl FlowsheetPropertyPackage {
    pub fn new(flowsheet: i32, property_package: i32, property_package_name: String) -> FlowsheetPropertyPackage {
        FlowsheetPropertyPackage {
            flowsheet,
            property_package,
            property_package_name,
        }
    }
}

