/*
 * Your Project API
 *
 * Your project description
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};


#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FlowsheetCompoundsBulkUpdate {
    #[serde(rename = "compounds")]
    pub compounds: Vec<i32>,
}

impl FlowsheetCompoundsBulkUpdate {
    pub fn new(compounds: Vec<i32>) -> FlowsheetCompoundsBulkUpdate {
        FlowsheetCompoundsBulkUpdate {
            compounds,
        }
    }
}

