/*
 * Your Project API
 *
 * Your project description
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FlowsheetCompound {
    #[serde(rename = "compound")]
    pub compound: i32,
    #[serde(rename = "flowsheet")]
    pub flowsheet: i32,
}

impl FlowsheetCompound {
    pub fn new(compound: i32, flowsheet: i32) -> FlowsheetCompound {
        FlowsheetCompound {
            compound,
            flowsheet,
        }
    }
}

