/*
 * Your Project API
 *
 * Your project description
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};


/// HeaterCalculationModeEnum : * `HeatAdded` - Heatadded * `OutletTemperature` - Outlettemperature * `EnergyStream` - Energystream * `OutletVaporFraction` - Outletvaporfraction * `TemperatureChange` - Temperaturechange * `HeatAddedRemoved` - Heataddedremoved
/// * `HeatAdded` - Heatadded * `OutletTemperature` - Outlettemperature * `EnergyStream` - Energystream * `OutletVaporFraction` - Outletvaporfraction * `TemperatureChange` - Temperaturechange * `HeatAddedRemoved` - Heataddedremoved
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum HeaterCalculationModeEnum {
    #[serde(rename = "HeatAdded")]
    HeatAdded,
    #[serde(rename = "OutletTemperature")]
    OutletTemperature,
    #[serde(rename = "EnergyStream")]
    EnergyStream,
    #[serde(rename = "OutletVaporFraction")]
    OutletVaporFraction,
    #[serde(rename = "TemperatureChange")]
    TemperatureChange,
    #[serde(rename = "HeatAddedRemoved")]
    HeatAddedRemoved,

}

impl std::fmt::Display for HeaterCalculationModeEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::HeatAdded => write!(f, "HeatAdded"),
            Self::OutletTemperature => write!(f, "OutletTemperature"),
            Self::EnergyStream => write!(f, "EnergyStream"),
            Self::OutletVaporFraction => write!(f, "OutletVaporFraction"),
            Self::TemperatureChange => write!(f, "TemperatureChange"),
            Self::HeatAddedRemoved => write!(f, "HeatAddedRemoved"),
        }
    }
}

impl Default for HeaterCalculationModeEnum {
    fn default() -> HeaterCalculationModeEnum {
        Self::HeatAdded
    }
}

