/*
 * Your Project API
 *
 * Your project description
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};


/// HeatExchangerCalculationModeEnum : * `CalcTempHotOut` - Calctemphotout * `CalcTempColdOut` - Calctempcoldout * `CalcBothTemp` - Calcbothtemp * `CalcBothTemp_UA` - Calcbothtemp Ua * `CalcArea` - Calcarea * `ShellandTube_Rating` - Shellandtube Rating * `ShellandTube_CalcFoulingFactor` - Shellandtube Calcfoulingfactor * `PinchPoint` - Pinchpoint * `ThermalEfficiency` - Thermalefficiency * `OutletVaporFraction1` - Outletvaporfraction1 * `OutletVaporFraction2` - Outletvaporfraction2
/// * `CalcTempHotOut` - Calctemphotout * `CalcTempColdOut` - Calctempcoldout * `CalcBothTemp` - Calcbothtemp * `CalcBothTemp_UA` - Calcbothtemp Ua * `CalcArea` - Calcarea * `ShellandTube_Rating` - Shellandtube Rating * `ShellandTube_CalcFoulingFactor` - Shellandtube Calcfoulingfactor * `PinchPoint` - Pinchpoint * `ThermalEfficiency` - Thermalefficiency * `OutletVaporFraction1` - Outletvaporfraction1 * `OutletVaporFraction2` - Outletvaporfraction2
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum HeatExchangerCalculationModeEnum {
    #[serde(rename = "CalcTempHotOut")]
    CalcTempHotOut,
    #[serde(rename = "CalcTempColdOut")]
    CalcTempColdOut,
    #[serde(rename = "CalcBothTemp")]
    CalcBothTemp,
    #[serde(rename = "CalcBothTemp_UA")]
    CalcBothTempUa,
    #[serde(rename = "CalcArea")]
    CalcArea,
    #[serde(rename = "ShellandTube_Rating")]
    ShellandTubeRating,
    #[serde(rename = "ShellandTube_CalcFoulingFactor")]
    ShellandTubeCalcFoulingFactor,
    #[serde(rename = "PinchPoint")]
    PinchPoint,
    #[serde(rename = "ThermalEfficiency")]
    ThermalEfficiency,
    #[serde(rename = "OutletVaporFraction1")]
    OutletVaporFraction1,
    #[serde(rename = "OutletVaporFraction2")]
    OutletVaporFraction2,

}

impl std::fmt::Display for HeatExchangerCalculationModeEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::CalcTempHotOut => write!(f, "CalcTempHotOut"),
            Self::CalcTempColdOut => write!(f, "CalcTempColdOut"),
            Self::CalcBothTemp => write!(f, "CalcBothTemp"),
            Self::CalcBothTempUa => write!(f, "CalcBothTemp_UA"),
            Self::CalcArea => write!(f, "CalcArea"),
            Self::ShellandTubeRating => write!(f, "ShellandTube_Rating"),
            Self::ShellandTubeCalcFoulingFactor => write!(f, "ShellandTube_CalcFoulingFactor"),
            Self::PinchPoint => write!(f, "PinchPoint"),
            Self::ThermalEfficiency => write!(f, "ThermalEfficiency"),
            Self::OutletVaporFraction1 => write!(f, "OutletVaporFraction1"),
            Self::OutletVaporFraction2 => write!(f, "OutletVaporFraction2"),
        }
    }
}

impl Default for HeatExchangerCalculationModeEnum {
    fn default() -> HeatExchangerCalculationModeEnum {
        Self::CalcTempHotOut
    }
}

