/*
 * Your Project API
 *
 * Your project description
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};


#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InputComposition {
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "flowsheetCompound")]
    pub flowsheet_compound: Box<models::FlowsheetCompound>,
    #[serde(rename = "compoundAmount")]
    pub compound_amount: Box<models::PropertyInfo>,
    #[serde(rename = "materialStream")]
    pub material_stream: i32,
}

impl InputComposition {
    pub fn new(id: i32, flowsheet_compound: models::FlowsheetCompound, compound_amount: models::PropertyInfo, material_stream: i32) -> InputComposition {
        InputComposition {
            id,
            flowsheet_compound: Box::new(flowsheet_compound),
            compound_amount: Box::new(compound_amount),
            material_stream,
        }
    }
}

