/*
 * Your Project API
 *
 * Your project description
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};


/// NameEnum : * `Peng-Robinson` - Peng Robinson * `NRTL` - Nrtl
/// * `Peng-Robinson` - Peng Robinson * `NRTL` - Nrtl
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum NameEnum {
    #[serde(rename = "Peng-Robinson")]
    PengRobinson,
    #[serde(rename = "NRTL")]
    Nrtl,

}

impl std::fmt::Display for NameEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::PengRobinson => write!(f, "Peng-Robinson"),
            Self::Nrtl => write!(f, "NRTL"),
        }
    }
}

impl Default for NameEnum {
    fn default() -> NameEnum {
        Self::PengRobinson
    }
}

