/*
 * Your Project API
 *
 * Your project description
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PressureDropCorrelationEnum : * `0` - Beggsbrill * `1` - Lockhartmartinelli * `2` - Petalasaziz
/// * `0` - Beggsbrill * `1` - Lockhartmartinelli * `2` - Petalasaziz
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PressureDropCorrelationEnum {
    #[serde(rename = "0")]
    Variant0,
    #[serde(rename = "1")]
    Variant1,
    #[serde(rename = "2")]
    Variant2,

}

impl std::fmt::Display for PressureDropCorrelationEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Variant0 => write!(f, "0"),
            Self::Variant1 => write!(f, "1"),
            Self::Variant2 => write!(f, "2"),
        }
    }
}

impl Default for PressureDropCorrelationEnum {
    fn default() -> PressureDropCorrelationEnum {
        Self::Variant0
    }
}

