/*
 * Your Project API
 *
 * Your project description
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PropertyPackage {
    #[serde(rename = "name")]
    pub name: models::NameEnum,
    #[serde(rename = "id")]
    pub id: i32,
}

impl PropertyPackage {
    pub fn new(name: models::NameEnum, id: i32) -> PropertyPackage {
        PropertyPackage {
            name,
            id,
        }
    }
}

