/*
 * Your Project API
 *
 * Your project description
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SolveRequest {
    #[serde(rename = "flowsheet_id")]
    pub flowsheet_id: i32,
    #[serde(rename = "debug", skip_serializing_if = "Option::is_none")]
    pub debug: Option<bool>,
    #[serde(rename = "require_variables_fixed", skip_serializing_if = "Option::is_none")]
    pub require_variables_fixed: Option<bool>,
}

impl SolveRequest {
    pub fn new(flowsheet_id: i32) -> SolveRequest {
        SolveRequest {
            flowsheet_id,
            debug: None,
            require_variables_fixed: None,
        }
    }
}

