/*
 * Your Project API
 *
 * Your project description
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ThermodynamicPathEnum : * `Adiabatic` - Adiabatic * `Polytropic` - Polytropic
/// * `Adiabatic` - Adiabatic * `Polytropic` - Polytropic
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ThermodynamicPathEnum {
    #[serde(rename = "Adiabatic")]
    Adiabatic,
    #[serde(rename = "Polytropic")]
    Polytropic,

}

impl std::fmt::Display for ThermodynamicPathEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Adiabatic => write!(f, "Adiabatic"),
            Self::Polytropic => write!(f, "Polytropic"),
        }
    }
}

impl Default for ThermodynamicPathEnum {
    fn default() -> ThermodynamicPathEnum {
        Self::Adiabatic
    }
}

