/*
 * Your Project API
 *
 * Your project description
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// TypeC3bEnum : * `3` - Conin * `1` - Conout * `0` - Conen * `2` - Consp
/// * `3` - Conin * `1` - Conout * `0` - Conen * `2` - Consp
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum TypeC3bEnum {
    #[serde(rename = "3")]
    Variant3,
    #[serde(rename = "1")]
    Variant1,
    #[serde(rename = "0")]
    Variant0,
    #[serde(rename = "2")]
    Variant2,

}

impl std::fmt::Display for TypeC3bEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Variant3 => write!(f, "3"),
            Self::Variant1 => write!(f, "1"),
            Self::Variant0 => write!(f, "0"),
            Self::Variant2 => write!(f, "2"),
        }
    }
}

impl Default for TypeC3bEnum {
    fn default() -> TypeC3bEnum {
        Self::Variant3
    }
}

